# Site Settings
title: Tech Notes
description: My personal knowledge base

# Theme Settings
remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
